# Generated by Django 5.2.7 on 2025-10-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='triplets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.FloatField()),
                ('bc', models.FloatField()),
                ('ac', models.FloatField()),
            ],
        ),
    ]
